### ISSUE TITLE
How to use Embed Flarum discussions as comments for your blog

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#129] opened 2020-08-01 19:56 UTC
Hello, How can i use this Embed in my website, what is the code and how to use it
i used this code : 
<iframe src="https://forum.wrdo.org/embed/2-test"></iframe>
Please take a look , how can i make the box more bigger , the size very small on the webiste
i used this link : 
https://www.freeflarum.com/docs/how-to/extensions/embed/
Thanks

**Comment by ghiathkamel** [comment] 2020-08-01 20:19
![Annotation 2020-08-01 161440](https://user-images.githubusercontent.com/60829719/89109835-ba667c80-d412-11ea-93ee-811d93a7d212.png)

**Comment by ghiathkamel** [comment] 2020-08-01 21:22
Thanks To GOD , i found how but i dont know how to do it auto size same as my site size 
i used this code
<iframe src="https://forum.wrdo.org/embed/2-test"  style="border:none;height:1280px;width:1280px"></iframe>

**Comment by CWKevo** [comment] 2020-08-02 00:13
If you want to adapt it to your site size, the simplest is just to use percents in the `width` and `height`, such as `90%` for example.

iFrame is a HTML tag and supports also CSS. You can learn more about them [here](https://www.w3schools.com/html/html_iframe.asp).

**Comment by quitd** [comment] 2020-08-02 07:38
You can probably use the 'Embed' extension

**Comment by CWKevo** [comment] 2020-08-02 07:42
> You can probably use the 'Embed' extension

That's what they had installed, they're asking how can they adapt the iFrame size to fit their forum. Note that there are also a plenty of tutorials on that topic on the internet.

**Comment by ghiathkamel** [comment] 2020-08-02 22:18
Thanks everyone

**Comment by ghiathkamel** [comment] 2020-08-03 02:52
i am using this code right now , is there any bug in my code , thanks .

<div>
<iframe id="form-iframe" src="https://forum.wrdo.org/embed/2-test" style="margin:0; width:100%; height:100%; border:none; overflow:hidden;" scrolling="yes" onload="AdjustIframeHeightOnLoad()"></iframe>

<script type="text/javascript">
function AdjustIframeHeightOnLoad() { document.getElementById("form-iframe").style.height = document.getElementById("form-iframe").contentWindow.document.body.scrollHeight + "px"; }
function AdjustIframeHeight(i) { document.getElementById("form-iframe").style.height = parseInt(i) + "px"; }
</script>

</div>

**Comment by CWKevo** [comment] 2020-08-03 03:05
You have specified `AdjustIframeHeight(i)` function that you didn't use, so you can remove that. Also note that the `scrolling` attribite in `<iframe>` tag is obsolete (you can remove `scrolling="yes"`.

```
document.getElementById("form-iframe").style.height = document.getElementById("form-iframe").contentWindow.document.body.scrollHeight + "px";
```
in `AdjustIframeHeightOnLoad()` function finds `form-iframe` and then assigns it a height of that same's iFrame. If you're trying to make the height of iFrame same as the page height you are embedding, then using the percents only might also work (no js). Have you tried that?

**Comment by ghiathkamel** [comment] 2020-08-03 03:11
yes you are right , only percents works, but i am using google site builder only to start up the project i cant do auto-resize height for embedded code :(
i was trying to do auto dynamic height for embedded code , but no luck .
Thank you very much for your time , GOD bless you all

**Comment by ghiathkamel** [comment] 2020-08-03 03:14
This is my new code is there anything missing : 
<iframe id="form-iframe" src="https://forum.wrdo.org/embed/2-test" style="margin:0; width:100%; height:100%; border:none; overflow:hidden;" </iframe>

Thanks

**Comment by CWKevo** [comment] 2020-08-03 03:29
That code looks great and should work the same. If not, try making the percentage smaller or bigger, depending on some other factors, such as size of your webpage (body width for example). You can use half of the full size (`50%`) or you can go higher, it depends on you. You can also use `px` (size in pixels), so such as `500px` instead of `50%`. You cane learn more about percents and heights [here](https://stackoverflow.com/questions/5657964/css-why-doesn-t-percentage-height-work).

As for the [margin](https://www.w3schools.com/css/css_margin.asp) and [overflow](https://www.w3schools.com/css/css_overflow.asp), you don't really need those. In short, margin defines how much space there is around the iFrame and overflow controls what happens to the content when it's too big. It controls the scrollbar too, in your case you have used the hidden attribute, meaning when the content of the frame is too big, it gets cut and there is no scrollbar to scroll through it to see the rest of the content, therefore I'd suggest you to remove `overflow` just for sure.

**Comment by ghiathkamel** [comment] 2020-08-03 04:19
Thanks i will use this code 
`<iframe src="https://forum.wrdo.org/embed/2-test" style="width: 100%; height: 100%; margin: 0; border: none;"></iframe>`
sorry iam still learing do i need to use those : 
padding:0
frameborder="0"
min-height:100%
min-width: 100%
is it good idea to set overflow:auto
What do you think 
Thanks :)

**Comment by ghiathkamel** [comment] 2020-08-03 04:23
i found this do i need to use it : 
`onload="resizeIframe(this);
<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.documentElement.scrollHeight + 'px';
  }
</script>`

**Comment by CWKevo** [comment] 2020-08-03 04:30
Padding is opposite of margin and defines how much "negative space" is around the object, eg. space inside of it. I believe this won't really make a huge change for iFrames, if any, so you don't really need to use those.

`frameborder` is deprecated and is the same as using `border` from CSS.

As for `min-height` and `min-width`, these might be useful in case sizes do not work as intended or are overwritten by another properties, however there is nothing that really manipulates your frame's width and height, so I guess you don't have to use those.

And yes, it is indeed a good idea to use `overflow: auto;` - this makes the scrollbar appear only when needed. Note that with another CSS, you can make the scrollbar disappear while keeping the scrolling behavior.

About the code, it works exactly the same as the JavaScript code you sent earlier, except that there are different variable names, but this does not change its functioning. I'd suggest you to use JavaScript when necessary, or when you want to change the height more dynamically and to better adapt to the page. If you are using just a Google site builder, I think the best idea would be to just tweak your CSS & HTML code accordingly to achieve the desired result instead.

**Comment by ghiathkamel** [comment] 2020-08-03 05:17
Thanks, i will use overflow: auto; :)
i was playing with this code to hide the scrollbar while keeping the scrolling behaviour, just want to see how it looks without scrollbar but not works
`-ms-overflow-style: none;scrollbar-height: none; display: none;`

**Comment by ghiathkamel** [comment] 2020-08-03 05:30
i am trying this code to hide the scrollbar but still not working 
![image](https://user-images.githubusercontent.com/60829719/89148819-dbb98c80-d528-11ea-97a6-dd5617667fae.png)
`
<iframe src="https://forum.wrdo.org/embed/4-welcome-to-world-research-and-development-organization-forum" style="width: 100%; height: 97%; margin: 0;overflow:auto; -ms-overflow-style: none;scrollbar-height: none;scrollbar-width: none; border: none; "></iframe>
`

**Comment by CWKevo** [comment] 2020-08-03 06:10
```html
/* Hide scrollbar for Chrome, Safari and Opera */
.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.example {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}
``` (from [this page](https://www.w3schools.com/howto/howto_css_hide_scrollbars.asp))

Different browsers have different ways to hide scrollbars and styles. If you want to have the biggest support amongst all the browsers, you must use every variation of the code.

Due to many different rules, it would be the best to just style it separately rather than putting all rules under 1 HTML tag.

Therefore this should work, we just have to change the code a bit:
```html
<iframe id="iframe" src="https://forum.wrdo.org/embed/4-welcome-to-world-research-and-development-organization-forum"></iframe>
<style>
#iframe {
  width: 100%;
  height: 97%;
  margin: 0;
  overflow: auto;
  scrollbar-width: none; /* Firefox /*
  /* Note: Scrollbars don't have a height property. */
  -ms-overflow-style: none;  /* IE and Edge */
  border: none;
}

#iframe::-webkit-scrollbar {
  display: none;
}
</style>
```

**Comment by ghiathkamel** [comment] 2020-08-04 01:18
Thank you very much for writing the code, much appreciated
i tried your code but still there is scroll visible as shown in the photo, its okay not big deal, but maybe without the scroll will be more cleaner 
![temp](https://user-images.githubusercontent.com/60829719/89242078-a8c9d400-d5ce-11ea-8dde-53a8e7808210.png)
Thanks

**Comment by ghiathkamel** [comment] 2020-08-04 01:27
i tried those codes in the link , but no luck , strange 
https://www.w3schools.com/cssref/css3_pr_overflow-y.asp

**Comment by CWKevo** [comment] 2020-08-04 03:27
`overflow` does not hide the scrollbar, it just controls the scrolling behavior. If you put `overflow: hidden;`, then you disable scrolling, therefore the scrollbar disappears too.

Also if Google Sites supports editing CSS styles, paste the CSS there. It might not work due to Google Sites not supporting it, but also my code could simply just not work. I can check it later.

**Comment by CWKevo** [comment] 2020-08-05 02:54
I'll close this, since the original question in the title was answered. There are many tutorials on the internet, you should check them too if you run into more problems.

**Comment by CWKevo** [comment] 2020-08-05 02:55
> I'll close this, since the original question in the title was answered. There are many tutorials on the internet, you should check them too if you run into more problems and just keep on trying with the codes.

**Closed by CWKevo** 2020-08-05 02:54 UTC
Labels: ❔  Question
