### ISSUE TITLE
zerosonesfun/direct-links

### ISSUE THREAD

**Issue by jgrillo2020** [gwillem/freeflarum.com#328] opened 2022-01-10 02:00 UTC
__Packagist URL for extension:__
https://packagist.org/packages/zerosonesfun/direct-links

__Why should we install the extension?__
Allows you to send links that lead to the signup page/ composer and create posts using links (like instagram and facebook), Opens the ability to send direct links to people, without having them to click on buttons.

**Comment by CWKevo** [comment] 2022-01-10 03:52
Duplicate of #326

**Closed by CWKevo** 2022-01-10 03:52 UTC
Labels: 🙋 Extension/feature request
