### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by defectiveshadow** [gwillem/freeflarum.com#169] opened 2020-11-21 04:25 UTC
https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community

[//]: # "https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/29"

__Why should we install this extension?__

It allows you to have a simple blog/portal for users and adds a huge amount of features to Flarum

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version:__ This extension is currently Flarum beta-13 only, beta-14 support will be added later.

**Comment by defectiveshadow** [comment] 2020-11-21 04:27
Sorry, new to github

**Comment by CWKevo** [comment] 2020-11-21 04:28
I've noticed it, seems cool. Might be added once it gets more upvotes

**Comment by enragedpopsicle** [comment] 2020-11-21 04:34
I'd love to have this

**Comment by defectiveshadow** [comment] 2020-11-21 04:39
Seems to be getting some attention at least.

**Comment by meetdilip** [comment] 2020-11-21 12:34
This addon is new and evolving. I think it will be nice to give the developer a window as there are a couple of bug fixes released already based on the initial feedback.

**Comment by bluenchanter** [comment] 2020-11-22 11:49
Wow its look awesome

**Comment by CWKevo** [comment] 2020-12-06 13:05
This will be installed when it becomes compatible with beta.14.1 and up. Also, as @meetdilip pointed out, it is quite new, so I think that it is right to just wait a bit :)

**Comment by ririko5834** [comment] 2020-12-07 09:30
Please add it

**Comment by CWKevo** [comment] 2020-12-07 09:33
> Please add it

![image](https://user-images.githubusercontent.com/39010496/101333988-9363ff80-3877-11eb-9848-6ff07854b19b.png)

> This will be installed when it becomes compatible with beta.14.1 and up.

**Comment by TulvL** [comment] 2020-12-28 17:35
I am also looking forward to this Extension being installed on freeflarum after the update by author

**Comment by CWKevo** [comment] 2020-12-28 17:37
It has received enough upvotes, and I am interested too.
It is planned to be updated early January, so I'll add it ASAP when that happens

**Comment by T0MMYRR** [comment] 2021-01-17 21:33
Wohooo the beta 15 update is here!! I can't wait to test this extension 😄 

I leave the link: https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/85

**Comment by CWKevo** [comment] 2021-01-18 04:46
I have to do some tests at our beta forum to see how this extension behaves on FreeFlarum, then we'll include it, since it has good amount of upvotes.

**Comment by CWKevo** [comment] 2021-01-18 04:58
Works well except for the night mode support, but since admins can tweak that, I just included it. I have to sync files now and after that I'll anniunce it on Discuss. As usual, if there will be serious problems caused by this extension, we will have to remove it.

**Closed by CWKevo** 2021-01-18 04:58 UTC
Labels: 🙋 Extension/feature request
