### ISSUE TITLE
Diff (Edit History)

### ISSUE THREAD

**Issue by quitd** [gwillem/freeflarum.com#119] opened 2020-07-23 16:11 UTC
__Packagist URL for extension:__
https://packagist.org/packages/the-turk/flarum-diff

__Why we should install this extension?__
1. useful ..?

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
Doesn't have the "Incompatible" tag at Flarum Discuss

**Comment by CWKevo** [comment] 2020-07-23 16:23
Great finding, certainly an extension that would be very welcoming for all Flarum forums, because as of right now, Flarum is absent of edit history and mistakes caused by editing cannot be reverted.

**Comment by AndreiJirohHaliliDev2006** [comment] 2020-08-30 12:57
Maybe we can also suggest to the Flarum devs to have an edit history built-in?

**Comment by quitd** [comment] 2020-08-30 13:23
> Maybe we can also suggest to the Flarum devs to have an edit history built-in?

yea
that'd be cool

**Comment by CWKevo** [comment] 2020-08-30 13:54
Yes, you can, but to be honest, there isn't a big chance that this will be merged into Flarum core anytime soon, if not ever. Flarum is meant to be kept simple and easily extendable by extensions, such as this one.

**Comment by CWKevo** [comment] 2020-09-12 15:38
Unfortunately, this extension cannot be installed because it conflicts with FreeFlarum (the `php-diff` module causes `500` error on all forums).

**Closed by CWKevo** 2020-09-12 15:38 UTC
Labels: 🙋  Extension/feature request

**Comment by CWKevo** [comment] 2022-03-20 18:54
Re-added
