### ISSUE TITLE
FoF Night mode

### ISSUE THREAD

**Issue by Geshii** [gwillem/freeflarum.com#88] opened 2020-04-22 13:42 UTC
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://github.com/FriendsOfFlarum/nightmode

__Why we should install this extension?__
- You should install it because with this extension, users can choose the forum theme
- I want this extension because i want my users to choose the theme they want.

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

> https://discuss.flarum.org/d/21492-friendsofflarum-night-mode
> https://i.imgur.com/ZJcDGQB.png

**Comment by gwillem** [comment] 2020-04-24 09:10
Duplicate of #52

**Closed by gwillem** 2020-04-24 09:10 UTC
Labels: 🙋  Extension/feature request
