### ISSUE TITLE
Verified badge

### ISSUE THREAD

**Issue by jgrillo2020** [gwillem/freeflarum.com#331] opened 2022-01-18 20:03 UTC
__Packagist URL for extension:__

https://packagist.org/packages/serakoi/flarum-verified-badge

__Why should we install the extension?__
Ads a simple front end verified badge that stands out from other permission groups

**Comment by CWKevo** [comment] 2022-01-18 20:05
Duplicate of #301

**Closed by CWKevo** 2022-01-18 20:05 UTC
Labels: 🙋 Extension/feature request
