### ISSUE TITLE
Login extensions are not shown in the login window.

### ISSUE THREAD

**Issue by csBlackWolf** [gwillem/freeflarum.com#81] opened 2020-04-06 19:21 UTC
**Describe the bug**
I have enabled the extensions to login through external services like Steam, GitHub, Discord etc. and set the API-Keys for all of them, but they are not shown at the login window.

**What is your FreeFlarum host name**
faq.flarum.cloud

**To Reproduce**
1. Go to 'extensions'
2. Click on 'activate' by the 'steam login' extension.
3. Set the API-Key that i got from steam.
4. Logout and klick on 'login' or 'register'.
5. No option for 'login with steam'

Same problem with other login extensions.

**Expected behavior**
"Login with Steam" option in the login window.

**Screenshots**
Screen from freeflarum:
https://abload.de/img/fireshotcapture037-dakqk4q.png

Screen from a test installation:
https://abload.de/img/fireshotcapture038-da3vjbt.png

**Comment by gwillem** [comment] 2020-04-07 07:17
They show up fine here. Perhaps you should flush your cache/cookies? 

![image](https://user-images.githubusercontent.com/1145479/78640759-905fdc00-78b0-11ea-897a-7fe3721531cb.png)

**Comment by csBlackWolf** [comment] 2020-04-10 12:35
I have cleared the full cache and all cookies, still can't see the log in extensions.
But it is working with Opera.

Strange...

Any ideas?

Firefox version is 75.0 (64-Bit)
(And yes, i have tried it with disabled addons.)

**Comment by xCustomWorld** [comment] 2020-04-14 10:21
All login options show fine for me too, I think the problem is inside your browser. Maybe you have some extension blocking the buttons (like AdBlock filter for example). Try browsing the page in incognito mode too.

There might be also incompatibility between the extension(s) and Firefox. Try to [open up the JavaScript console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) and look for errors. If there are any, send them, maybe we can deduct something.

**Comment by gwillem** [comment] 2020-04-24 09:37
Closing because we cannot reproduce

**Closed by gwillem** 2020-04-24 09:37 UTC
Labels: 🐞  Bug
